version: 2.1

orbs:
  docker-agents: feedyard/docker-agents@dev:0.0.7-rc1

workflows:
  circleci-orb-agent-image-pipeline:
    jobs:
      - docker-agents/publish:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - docker-agents/release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
